import "dotenv/config";
import * as sqlite from "./schema.sqlite";
import * as postgres from "./schema.pg";

const usePostgres = (process.env.DATABASE_URL || "").startsWith("postgres");
const runtime = usePostgres ? postgres : sqlite;

export const roles = runtime.roles as any;
export const users = runtime.users as any;
export const subjects = runtime.subjects as any;
export const grades = runtime.grades as any;
export const courses = runtime.courses as any;
export const chapters = runtime.chapters as any;
export const lessons = runtime.lessons as any;
export const documents = runtime.documents as any;
export const aiJobs = runtime.aiJobs as any;
export const experiments = runtime.experiments as any;
export const exercises = runtime.exercises as any;
export const questions = runtime.questions as any;
export const answers = runtime.answers as any;
export const progress = runtime.progress as any;
export const achievements = runtime.achievements as any;
export const studentAchievements = runtime.studentAchievements as any;
export const learnerProfiles = runtime.learnerProfiles as any;
export const conceptMastery = runtime.conceptMastery as any;
export const learningEvents = runtime.learningEvents as any;
export const flashcards = runtime.flashcards as any;
export const flashcardReviews = runtime.flashcardReviews as any;
export const aiConversations = runtime.aiConversations as any;
export const aiMessages = runtime.aiMessages as any;
export const recommendations = runtime.recommendations as any;
export const teacherAiConversations = runtime.teacherAiConversations as any;
export const teacherAiMessages = runtime.teacherAiMessages as any;
export const examPlans = runtime.examPlans as any;
export const mockExams = runtime.mockExams as any;
export const earlyWarningSignals = runtime.earlyWarningSignals as any;
export const interventions = runtime.interventions as any;
export const classes = runtime.classes as any;
export const enrollments = runtime.enrollments as any;
export const xpTransactions = runtime.xpTransactions as any;
export const assignments = runtime.assignments as any;
export const studentAssignments = runtime.studentAssignments as any;
export const notifications = runtime.notifications as any;
export const auditLogs = runtime.auditLogs as any;
